name: test-bot
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    strategy:
      matrix:
        os: [macos-latest, ubuntu-24.04]
      fail-fast: false

    runs-on: ${{ matrix.os }}

    steps:
      - name: Set up Homebrew
        uses: Homebrew/actions/setup-homebrew@1f8e202ffddf94def7f42f6fa3a482e821489f9c

      - name: Install from source
        run: |
          brew install --build-from-source --verbose turtton/tap/cnowledje

      - name: Run formula test
        run: |
          brew test --verbose cnowledje

      - name: Audit formula
        run: |
          brew audit --strict --online cnowledje
